# Generated by Django 5.1.6 on 2025-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='63c157', max_length=6),
        ),
    ]
