# Generated by Django 5.1.6 on 2025-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('alert_status', models.CharField(choices=[('Low Stock', '🔴 Low Stock'), ('Near Expiry', '⏳ Near Expiry'), ('OK', '✅ OK')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b91c4f', max_length=6),
        ),
    ]
