# Generated by Django 5.1.6 on 2025-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0003_medicine_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacy_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5d2056', max_length=6),
        ),
    ]
