# Generated by Django 5.1.6 on 2025-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0004_medicine_pharmacy_name_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fb32a7', max_length=6),
        ),
    ]
