# Generated by Django 5.1.6 on 2025-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0006_salesentry_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('cart_product', models.CharField(max_length=255)),
                ('cart_quantity', models.PositiveIntegerField()),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesentry',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='salesentry',
            name='pharmacy_name',
            field=models.CharField(default='pharmacy', max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7581f2', max_length=6),
        ),
    ]
