# Generated by Django 5.1.6 on 2025-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0007_cartinfo_remove_salesentry_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day', models.DateField(auto_now_add=True)),
                ('week', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='48fd89', max_length=6),
        ),
    ]
