# Generated by Django 5.1.6 on 2025-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0008_salessummary_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='day',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='month',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='week',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='58e08e', max_length=6),
        ),
    ]
