# Generated by Django 5.1.6 on 2025-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0009_salesentry_day_salesentry_month_salesentry_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a21df6', max_length=6),
        ),
    ]
