# Generated by Django 5.1.6 on 2025-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0011_alter_otptoken_otp_code_alter_salesentry_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cd458b', max_length=6),
        ),
    ]
