# Generated by Django 5.1.6 on 2025-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0012_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='daily_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='monthly_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='weekly_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='04c5f9', max_length=6),
        ),
    ]
