# Generated by Django 5.1.6 on 2025-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0013_salesentry_daily_sales_salesentry_monthly_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d49bd0', max_length=6),
        ),
    ]
