# Generated by Django 5.1.6 on 2025-05-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0014_salesentry_sales_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ed675b', max_length=6),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='daily_sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='monthly_sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='weekly_sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
