# Generated by Django 5.1.6 on 2025-05-26 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0016_alter_otptoken_otp_code_alter_salesentry_daily_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesentry',
            name='monthly_sales',
        ),
        migrations.RemoveField(
            model_name='salesentry',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salesentry',
            name='weekly_sales',
        ),
        migrations.AddField(
            model_name='salesentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='73800b', max_length=6),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='daily_sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='day',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='month',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='week',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
