# Generated by Django 5.1.6 on 2025-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0017_remove_salesentry_monthly_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6756c9', max_length=6),
        ),
    ]
