# Generated by Django 5.1.6 on 2025-05-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0018_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b5a132', max_length=6),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
