# Generated by Django 5.1.6 on 2025-05-26 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0019_alter_otptoken_otp_code_alter_salesentry_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('expected_date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_name', models.CharField(max_length=255)),
                ('day', models.PositiveIntegerField(editable=False, null=True)),
                ('month', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], max_length=20)),
                ('day', models.PositiveIntegerField(editable=False, null=True)),
                ('month', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('day', models.PositiveIntegerField(editable=False, null=True)),
                ('month', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='24af4d', max_length=6),
        ),
    ]
