# Generated by Django 5.1.6 on 2025-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0020_incomingstock_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessummary',
            name='day',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c59313', max_length=6),
        ),
    ]
