# Generated by Django 5.1.6 on 2025-05-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0021_remove_salessummary_day_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e43107', max_length=6),
        ),
    ]
