# Generated by Django 5.1.6 on 2025-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0022_remove_supplier_created_at_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='50438c', max_length=6),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='day',
            field=models.DateField(editable=False, null=True),
        ),
    ]
