# Generated by Django 5.1.6 on 2025-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0023_alter_otptoken_otp_code_alter_supplier_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fa7369', max_length=6),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='day',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
