# Generated by Django 5.1.6 on 2025-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0024_alter_otptoken_otp_code_alter_supplier_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8c2546', max_length=6),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
