# Generated by Django 5.1.6 on 2025-05-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0025_alter_otptoken_otp_code_alter_purchaseorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6554ff', max_length=6),
        ),
    ]
