# Generated by Django 5.1.6 on 2025-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0026_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2b4384', max_length=6),
        ),
    ]
