# Generated by Django 5.1.6 on 2025-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0027_remove_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6dec1e', max_length=6),
        ),
    ]
