# Generated by Django 5.1.6 on 2025-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0029_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='518394', max_length=6),
        ),
    ]
