# Generated by Django 5.1.6 on 2025-05-27 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0032_customer_alter_otptoken_otp_code_purchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total',
        ),
        migrations.AddField(
            model_name='customer',
            name='pharmacy_name',
            field=models.CharField(default='Main Branch', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='pharmacy_name',
            field=models.CharField(default='Main Branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a0df6c', max_length=6),
        ),
    ]
