# Generated by Django 5.1.6 on 2025-05-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0033_remove_purchasehistory_total_customer_pharmacy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7db7e2', max_length=6),
        ),
    ]
