# Generated by Django 5.1.6 on 2025-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0034_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='date',
            new_name='expected_date',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3e8d3c', max_length=6),
        ),
    ]
