# Generated by Django 5.1.6 on 2025-05-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0035_rename_date_purchasehistory_expected_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='28a418', max_length=6),
        ),
    ]
