# Generated by Django 5.1.6 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0036_remove_purchasehistory_purchase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_metric', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('patient_impact', models.TextField()),
                ('data_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reporting_period', models.CharField(max_length=100)),
                ('target_kpi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=100)),
                ('submitted_to', models.CharField(max_length=255)),
                ('compliance_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_system', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('example_vendors', models.CharField(max_length=255)),
                ('integration_notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='79ef3e', max_length=6),
        ),
    ]
