# Generated by Django 5.1.6 on 2025-05-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0039_drug_suplier_remove_orderrequest_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiryalert',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='lowstockalert',
            name='drug',
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='medicine',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='ores.medicine'),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='medicine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='ores.medicine'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1693be', max_length=6),
        ),
    ]
