# Generated by Django 5.1.6 on 2025-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0040_remove_expiryalert_drug_remove_lowstockalert_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='normal', max_length=5),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8aaded', max_length=6),
        ),
    ]
