# Generated by Django 5.1.6 on 2025-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0041_customuser_role_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5fddd1', max_length=6),
        ),
    ]
