# Generated by Django 5.1.6 on 2025-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ores', '0042_alter_customuser_role_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7e2e30', max_length=6),
        ),
    ]
